- name: kick
  machine: sv.machines.beats.detroit.Detroit
  type: sample
  temperature: 0.5
  density: 0.5
- name: clap
  machine: sv.machines.beats.detroit.Detroit
  type: sample
  temperature: 0.25
  density: 0.25
- name: hat
  machine: sv.machines.beats.detroit.Detroit
  type: sample
  temperature: 0.75
  density: 0.75
